#!/bin/bash

# Create a list of include paths for qtcreator's static analyzer.
# Not required for building the project, it just helps working on the source.
for word in $(pkg-config --cflags-only-I clutter-1.0 atspi-2 libcanberra gio-2.0 gobject-2.0 gtk+-3.0 icu-uc pangocairo librsvg-2.0 libudev wayland-client x11 xkbcommon xkbfile xtst libxml-2.0 hunspell); do echo ${word:2}; done | sort | uniq

